In [2]:
import h5py as h5
import numpy as np

In [3]:
#ds = h5.File("../data/subData2D.h5","r")
ds = h5.File("../data/data2D_gzipped_famfiles_%d.h5","r",driver='family', memb_size=2500*10**6)
xFile = np.load("../data/inputMatrix.npz")
yFile = np.load("../data/Solution.npz")

In [26]:
x_test_raw = xFile["inputMatrix"]
for i in range(22):
    print(len(np.unique(x_test_raw[i,:,:,3])))
    #print(x_test_raw[i,:,:,3:5])
    

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [4]:
for key1 in ds.keys():
    for key2 in ds[key1].keys():
        if key2[0]=="x":
            x_raw = ds[key1][key2][:]
#             for i in range(x_raw.shape[0]-1):
#                 print(len(np.unique(x_raw[i][:,:,3])))
            print(np.unique(x_raw[:,0,0,3]))
            break
        

[1.65105536e-05 8.51374651e-05 1.44825756e-04 ... 4.99958799e-01
 4.99969294e-01 4.99980522e-01]
[0.0018369  0.00210751 0.00540701 0.00588506 0.00669383 0.0071535
 0.00779595 0.0079014  0.01385509 0.02132024 0.02243522 0.02438784
 0.03051785 0.04124526 0.05008317 0.05511384 0.06132158 0.06725203
 0.07363662 0.07826221 0.09618534 0.10097842 0.11012422 0.1102049
 0.11789936 0.13886256 0.14062908 0.14589317 0.14858069 0.14892669
 0.15118018 0.15660676 0.18149225 0.20632013 0.21114081 0.21364095
 0.21483646 0.21626391 0.22017774 0.22814405 0.24286412 0.25174008
 0.27823331 0.28401602 0.28561403 0.32500882 0.32908303 0.32963918
 0.35000231 0.35762197 0.37884997 0.39606299 0.40019461 0.40180572
 0.40273367 0.43123285 0.44480521 0.44728812 0.46653164 0.47186399
 0.48609088 0.48947919 0.4927249  0.49910763]
[0.00250275 0.00587832 0.01812982 0.03095509 0.03244259 0.04637457
 0.05054905 0.05356598 0.05451367 0.07198126 0.07425895 0.07521907
 0.10815992 0.10951769 0.11474298 0.11488143 0.12179994

In [ ]:
print(len(ds["random"].keys()))

In [8]:
x_data = ds[""]

['y1146',
 'y1340',
 'y1102',
 'y1300',
 'y1157',
 'x103',
 'x1227',
 'x1091',
 'x1107',
 'y1263',
 'y1355',
 'y1326',
 'x118',
 'y1080',
 'x12',
 'x1311',
 'x1327',
 'x1007',
 'y1269',
 'x1008',
 'y1001',
 'y1306',
 'x1032',
 'x1294',
 'y1322',
 'x1211',
 'x1224',
 'y1351',
 'y1124',
 'x1303',
 'x1218',
 'x1345',
 'y1268',
 'y1145',
 'x1293',
 'y1342',
 'x13',
 'y1086',
 'y1252',
 'y1182',
 'x1298',
 'y1179',
 'y1',
 'y1243',
 'x1168',
 'y1334',
 'x1287',
 'x1037',
 'y1052',
 'y1314',
 'y1282',
 'x1013',
 'x1187',
 'x1322',
 'x1106',
 'x128',
 'y109',
 'y1033',
 'y128',
 'x101',
 'x1080',
 'y1125',
 'y1216',
 'y1337',
 'x1278',
 'x1275',
 'x1073',
 'y1325',
 'x1282',
 'y1254',
 'y1135',
 'y1247',
 'y1319',
 'y1111',
 'x11',
 'y1350',
 'y1100',
 'x1329',
 'y1211',
 'y1316',
 'x1271',
 'y1261',
 'x1144',
 'y1241',
 'y1117',
 'x1000',
 'x1006',
 'y1029',
 'x1028',
 'x1042',
 'x1302',
 'y1141',
 'x1237',
 'x1342',
 'y1057',
 'y1237',
 'y1244',
 'x102',
 'y1187',
 'x1344',
 'y1051',
 'x101

In [6]:
key1 = list(ds.keys())
for key1_index in range(len(key1)):
    x_count = 0
    y_count = 0
    key2 = list(ds[key1[key1_index]].keys())
    for key2_index in range(len(key2)):
        if key2[key2_index].find("x")>=0:
            x_count+=1
        else :
            y_count+=1
    print("x:",end="")
    print(x_count)
    print("y:",end="")
    print(y_count)
#     for key2_index in range(len(key2)):
#         if ds[key1[key1_index]][key2[key2_index]].shape[0]>64:
#             continue
#         if key2[key2_index].find("x")>=0:
#             x_raw = ds[key1[key1_index]][key2[key2_index]][:]
#             x_mean = np.mean(x_raw,axis=(0,1,2))
#             x_max = np.amax(x_raw,axis=(0,1,2))
#             x_normed = (x_raw-x_mean)/x_max
#             print(x_normed[0][0][0])
#         else:
#             y_raw = ds[key1[key1_index]][key2[key2_index]][:]
#             y_mean = np.mean(y_raw,axis=())
#             y_max = np.max(y_raw,axis=())
#             y_min = np.min(y_raw,axis=())
#             y_normed = (y_raw-y_mean)/y_max
#             print(y_normed[0])
    for key2_index in range(int(len(key2)/2)):   #0-399 or 0-199
        if ds[key1[key1_index]][key2[key2_index]].shape[0]>64:
            continue
        x_raw = ds[key1[key1_index]][key2[key2_index]][:]
        y_raw = ds[key1[key1_index]][key2[key2_index+int(len(key2)/2)]][:]
        
        x_mean = np.mean(x_raw,axis=(0,1,2))
        x_max = np.amax(x_raw,axis=(0,1,2))
        x_normed = (x_raw-x_mean)/x_max

        y_mean = np.mean(y_raw,axis=())
        y_max = np.max(y_raw,axis=())
        y_min = np.min(y_raw,axis=())
        y_normed = (y_raw-y_mean)/y_max
        
        print(x_normed.shape)
        print(y_normed.shape)



x:400
y:400


IndexError: tuple index out of range

In [5]:
x_data = ds["x0"][:10]
y_data = ds["y0"][:10]

In [10]:
x_mean = np.mean(x_data,axis=(0,1,2))
y_mean = np.mean(y_data,axis=(0))

x_max = np.amax(x_data,axis=(0,1,2))
y_max = np.amax(y_data,axis=())

x_data_normed = (x_data-x_mean)/x_max
y_data_normed = (y_data-y_mean)/y_max

print(x_data_normed[0][0][0])
print(y_data_normed[0])

[-0.41210817  0.38480968 -0.33161349 -0.32458534  0.39380595]
[ 0.06083984+1.05526581e-10j  0.06548954+2.67125710e-10j
 -0.05626038-4.20218665e-10j -0.00651869-1.87201629e-10j
  0.0805452 +8.53956517e-10j  0.01680174-4.02379796e-10j
 -0.00583209-9.69184955e-10j -0.01070392+8.24052659e-10j
 -0.02313871+4.65153277e-10j  0.00087227-8.10446571e-11j
  0.00066788+1.47920079e-10j -0.01407879+7.76253783e-10j
  0.00686592-2.70700018e-10j -0.01155968-8.04912026e-10j
 -0.0115214 +1.78199483e-10j  0.03795958-3.12594867e-10j
  0.03723212+1.38903400e-09j  0.0346329 -5.74232328e-10j
  0.00807413+5.23586952e-10j -0.00108823+4.94144003e-10j
  0.00573726-1.32530575e-09j  0.00225191+1.27417910e-10j
  0.0027094 -4.23051372e-10j -0.00259438+1.30844724e-09j
 -0.0041884 +4.38456160e-10j  0.01458388-1.08779197e-09j
  0.01714471-1.97406369e-10j  0.01336842-3.87590932e-10j
  0.01612188+2.86838264e-09j  0.00359083+1.14164594e-10j
  0.00895892+3.16469906e-10j  0.01273617+5.49186530e-10j
  0.00689678-1.33622613e-0

In [51]:
x_ds = np.load("../data/inputMatrix.npz")
y_ds = np.load("../data/Solution.npz")

# print("input:")
# for key in list(x_ds.keys()):
#     print(key,":")
#     print(x_ds[key].shape)
    
# for key in list(y_ds.keys()):
#     print(key,":")
#     print(y_ds[key].shape)
print(y_ds["frequency1"][:,:50].shape)


(22, 50)


In [35]:
x1 = np.array([0,1,1,3,76,5])
x2 = np.array([[-9,1,8,3,4,4]])
test = np.vstack([x1,x2])
print(test.shape)
print(np.amax(test,axis=(0)))

(2, 6)
[ 0  1  8  3 76  5]


In [53]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.flatten())

[1 2 3 4 5 6 7 8]


In [10]:
a = "x0"
b = a[1:]
print(b)

0
